# Generated by Django 4.2.2 on 2023-06-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost", name="date", field=models.DateField(auto_now=True),
        ),
    ]
