# Generated by Django 4.2.2 on 2023-06-14 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0003_comments"),
    ]

    operations = [
        migrations.RemoveField(model_name="comments", name="post",),
        migrations.AddField(
            model_name="blogpost",
            name="comments",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="Blog.comments",
            ),
            preserve_default=False,
        ),
    ]
