# Generated by Django 4.2.2 on 2023-06-14 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0004_remove_comments_post_blogpost_comments"),
    ]

    operations = [
        migrations.RemoveField(model_name="blogpost", name="comments",),
        migrations.AddField(
            model_name="comments",
            name="post",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="Blog.blogpost",
            ),
            preserve_default=False,
        ),
    ]
