# Generated by Django 4.2.2 on 2023-06-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0003_delete_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
