# Generated by Django 4.2.2 on 2023-06-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0005_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone_no",
            field=models.IntegerField(null=True),
        ),
    ]
